import enum


class KeyboardKey(enum.Enum):
    """Supporting the ANSI layout"""

    KEY_ESCAPE = "KEY_ESCAPE"
    KEY_F1 = "KEY_F1"
    KEY_F2 = "KEY_F2"
    KEY_F3 = "KEY_F3"
    KEY_F4 = "KEY_F4"
    KEY_F5 = "KEY_F5"
    KEY_F6 = "KEY_F6"
    KEY_F7 = "KEY_F7"
    KEY_F8 = "KEY_F8"
    KEY_F9 = "KEY_F9"
    KEY_F10 = "KEY_F10"
    KEY_F11 = "KEY_F11"
    KEY_F12 = "KEY_F12"
    KEY_PRINT_SCREEN = "KEY_PRINT_SCREEN"
    KEY_F13 = KEY_PRINT_SCREEN
    KEY_SCROLL_LOCK = "KEY_SCROLL_LOCK"
    KEY_F14 = KEY_SCROLL_LOCK
    KEY_PAUSE = "KEY_PAUSE"
    KEY_F15 = KEY_PAUSE

    KEY_GRAVE = "KEY_GRAVE"
    KEY_BACKTICK = KEY_GRAVE
    KEY_1 = "KEY_1"
    KEY_2 = "KEY_2"
    KEY_3 = "KEY_3"
    KEY_4 = "KEY_4"
    KEY_5 = "KEY_5"
    KEY_6 = "KEY_6"
    KEY_7 = "KEY_7"
    KEY_8 = "KEY_8"
    KEY_9 = "KEY_9"
    KEY_0 = "KEY_0"
    KEY_MINUS = "KEY_MINUS"
    KEY_DASH = KEY_MINUS
    KEY_EQUALS = "KEY_EQUALS"
    KEY_BACKSPACE = "KEY_BACKSPACE"
    KEY_INSERT = "KEY_INSERT"
    KEY_HOME = "KEY_HOME"
    KEY_PAGE_UP = "KEY_PAGE_UP"
    KEY_NUMLOCK = "KEY_NUMLOCK"
    KEY_NUMPAD_DIVIDE = "KEY_NUMPAD_DIVIDE"
    KEY_NUMPAD_SLASH = KEY_NUMPAD_DIVIDE
    KEY_NUMPAD_MULTIPLY = "KEY_NUMPAD_MULTIPLY"
    KEY_NUMPAD_STAR = KEY_NUMPAD_MULTIPLY
    KEY_NUMPAD_SUBTRACT = "KEY_NUMPAD_SUBTRACT"
    KEY_NUMPAD_DASH = KEY_NUMPAD_SUBTRACT

    KEY_TAB = "KEY_TAB"
    KEY_Q = "KEY_Q"
    KEY_W = "KEY_W"
    KEY_E = "KEY_E"
    KEY_R = "KEY_R"
    KEY_T = "KEY_T"
    KEY_Y = "KEY_Y"
    KEY_U = "KEY_U"
    KEY_I = "KEY_I"
    KEY_O = "KEY_O"
    KEY_P = "KEY_P"
    KEY_LEFT_BRACKET = "KEY_LEFT_BRACKET"
    KEY_RIGHT_BRACKET = "KEY_RIGHT_BRACKET"
    KEY_BACKSLASH = "KEY_BACKSLASH"
    KEY_DELETE = "KEY_DELETE"
    KEY_END = "KEY_END"
    KEY_PAGE_DOWN = "KEY_PAGE_DOWN"
    KEY_NUMPAD_7 = "KEY_NUMPAD_7"
    KEY_NUMPAD_8 = "KEY_NUMPAD_8"
    KEY_NUMPAD_9 = "KEY_NUMPAD_9"
    KEY_NUMPAD_ADD = "KEY_NUMPAD_ADD"
    KEY_NUMPAD_PLUS = KEY_NUMPAD_ADD

    KEY_CAPSLOCK = "KEY_CAPSLOCK"
    KEY_A = "KEY_A"
    KEY_S = "KEY_S"
    KEY_D = "KEY_D"
    KEY_F = "KEY_F"
    KEY_G = "KEY_G"
    KEY_H = "KEY_H"
    KEY_J = "KEY_J"
    KEY_K = "KEY_K"
    KEY_L = "KEY_L"
    KEY_SEMICOLON = "KEY_SEMICOLON"
    KEY_APOSTROPHE = "KEY_APOSTROPHE"
    KEY_RETURN = "KEY_RETURN"
    KEY_ENTER = KEY_RETURN
    KEY_NUMPAD_4 = "KEY_NUMPAD_4"
    KEY_NUMPAD_5 = "KEY_NUMPAD_5"
    KEY_NUMPAD_6 = "KEY_NUMPAD_6"

    KEY_LEFT_SHIFT = "KEY_LEFT_SHIFT"
    KEY_Z = "KEY_Z"
    KEY_X = "KEY_X"
    KEY_C = "KEY_C"
    KEY_V = "KEY_V"
    KEY_B = "KEY_B"
    KEY_N = "KEY_N"
    KEY_M = "KEY_M"
    KEY_COMMA = "KEY_COMMA"
    KEY_PERIOD = "KEY_PERIOD"
    KEY_SLASH = "KEY_SLASH"
    KEY_RIGHT_SHIFT = "KEY_RIGHT_SHIFT"
    KEY_UP = "KEY_UP"
    KEY_NUMPAD_1 = "KEY_NUMPAD_1"
    KEY_NUMPAD_2 = "KEY_NUMPAD_2"
    KEY_NUMPAD_3 = "KEY_NUMPAD_3"
    KEY_NUMPAD_RETURN = "KEY_NUMPAD_RETURN"
    KEY_NUMPAD_ENTER = KEY_NUMPAD_RETURN

    KEY_LEFT_CTRL = "KEY_LEFT_CTRL"
    KEY_LEFT_SUPER = "KEY_LEFT_SUPER"
    KEY_LEFT_WINDOWS = KEY_LEFT_SUPER
    KEY_LEFT_ALT = "KEY_LEFT_ALT"
    KEY_SPACE = "KEY_SPACE"
    KEY_RIGHT_ALT = "KEY_RIGHT_ALT"
    KEY_RIGHT_SUPER = "KEY_RIGHT_SUPER"
    KEY_RIGHT_WINDOWS = KEY_RIGHT_SUPER
    KEY_APP_MENU = "KEY_APP_MENU"
    KEY_RIGHT_CTRL = "KEY_RIGHT_CTRL"
    KEY_LEFT = "KEY_LEFT"
    KEY_DOWN = "KEY_DOWN"
    KEY_RIGHT = "KEY_RIGHT"
    KEY_NUMPAD_0 = "KEY_NUMPAD_0"
    KEY_NUMPAD_DECIMAL = "KEY_NUMPAD_DECIMAL"
    KEY_NUMPAD_PERIOD = KEY_NUMPAD_DECIMAL

    # macOS
    KEY_FN = "KEY_FN"